### ISSUE TITLE
[FEATURE] Can you block reels and stories?

### ISSUE THREAD

**Issue by hyperlogos** [tiratatp/facebook_adblock#115]
It would be very helpful if this extension could block reels and stories, so I wouldn't need to use any other tools to suppress unwanted content on Fb.

**Comment by cbotsikas** [comment]
Thanks for the suggestion @hyperlogos. This is out of the scope of the plugin but it could be an optional setting to hide those too. For sure, we are never going to hide them by default, since reels and stories are not ads, similar to [suggested content](https://github.com/facebook-adblock/facebook_adblock/issues/62).

Feel free to submit a pull request

**Comment by Dark3n89** [comment]
> It would be very helpful if this extension could block reels and stories, so I wouldn't need to use any other tools to suppress unwanted content on Fb.

Feels and stories  you can block manual by any css or ad block, not dynamic minimal 4 moths

example stories: 

div.gs1a9yip.j83agx80.btwxx1t3.owycx6da.jifvfom9.dlv3wnog.rl04r1d5.ni8dbmo4.stjgntxs.jbae33se.cxgpxx05.l9j0dhe7 
{
Display: none !important;
visibility: hidden !important;
}

choice one from two rullez, i using 99% times display, but visibility work much better  for stories

**Comment by tiratatp** [comment]
Thanks for sharing. Feel free to submit a PR for this feature or fork this extension. As I stated before, our goal is to block targeted ads, and not anything else.

**Comment by m-czyz** [comment]
From my perspective this reels section could be considered in the same way as a other kind of adverts - both are undesirable by its nature.
