### ISSUE TITLE
[BUG] ads in my timeline, again

### ISSUE THREAD

**Issue by Conan179** [tiratatp/facebook_adblock#125]
hi, just wanted to let you know that the advertising and the "Sponsored" box at the top right are back.

**Comment by dima6526** [comment]
same here...

**Comment by AlgorithMan-de** [comment]
same here.
I don't know how it worked before, but I have examined the "Gesponsert"-tag (german) and I noticed that facebook obfuscates the text in there. There was a `<span>` with 42 sub-spans, which contained one character each. They were in random order, but the spans have `style="order: ..."` which puts them in the correct order. Also there are additional characters, which I guess are made invisible via the `class` attribute.

I'll attach a file with the exported HTML Element after sorting the spans by their `style="order:..."` tags.
In the last line, I have extracted the characters and highlight the "G", "e", "s", "p", "o", "n", "s", "e", "r", "t" in there.
[facebook_ads.txt](https://github.com/facebook-adblock/facebook_adblock/files/8886180/facebook_ads.txt)

I don't think it's necessary to decrypt the text, since the "sponsored" boxes seem to be the only timeline elements that have so many sub-tags.

**Comment by isaactzab** [comment]
I made a fix that probably solve the problem in your language. Please check it out. It currently works for spanish facebook.

**Comment by Dark3n89** [comment]
> I made a fix that probably solve the problem in your language. Please check it out. It currently works for spanish facebook.

I rewrite by your changes and all now work perfect, BIG thank you BOSS ♥
![image](https://user-images.githubusercontent.com/48175529/174173048-9cda035b-cd4a-4d69-beda-dbb13c976c5d.png)

**Comment by isaactzab** [comment]
awesome! Hopefully, the PR will be approved.
@tiratatp Let me know if any additional adjustments are needed to this PR

**Comment by tiratatp** [comment]
> awesome! Hopefully, the PR will be approved. @tiratatp Let me know if any additional adjustments are needed to this PR

Thank you for the fix @isaactzab !
Posted one minor comment. Could you fix that and I can merge it today?

**Comment by tiratatp** [comment]
Released as v1.9.11 

Thanks all!

**Comment by Conan179** [comment]
On the german facebook site, its not working.

**Comment by Conan179** [comment]
![fa_190622](https://user-images.githubusercontent.com/1906242/174475287-44eb16fb-de3b-499e-b099-00664ffdc128.JPG)

**Comment by isaactzab** [comment]
I tried to replicate and indeed, in the Spanish version the advertisement came up again. I did npm install, then npm run release, reloaded the extension and it worked fine. The advertisement is gone. Probably you have some issue with the build.

**Comment by isaactzab** [comment]
I am not sure if the chrome extension store version is the same as the repository version. can you confirm that @tiratatp ?
