### ISSUE TITLE
Cannot test 

### ISSUE THREAD

**Issue by davidlindercodes** [tiratatp/facebook_adblock#63]
Hi there, 

Nice extension, I really like how your code is set up. I downloaded the files from github, and want to try and make some changes to the code for a [personal project ](https://github.com/davidlindercodes/Facebook-Ad-Hunter)I'm working on, fisrt I'm trying to test the github files, makes sure it is all there and working, but when I try to load unpacked extension to chrome I am getting the error:
"File
~/Documents/GitHub/facebook_adblock
Error
Could not load javascript 'content.js' for content script.
Could not load manifest."

Any suggestion on how to fix this?

Much appreciated.

**Comment by cbotsikas** [comment]
Hi David,
In order to load it on Chrome or Firefox, you first need to build the extension. 
In order to do so, you'll need to have installed on your system Node.js with npm. Then you need to download all the required building tools, use `npm install` in the project's root directory and finally you need to build the extension using `npm run build` command. If everything was successful, you should have a `dist/src/` folder which you can use to load the unpacked version. In your case, it should be `~/Documents/GitHub/facebook_adblock/dist/src/`
